#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Holberton School'

apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
