#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Hello World!'

sudo su
apt-get update
apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
