#!/usr/bin/env bash
# Install nginx and and make it return a page with a string 'Holberton School'
# Make sure that the '/redirect_me' url is a permanent redirect

sudo su
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line1="rewrite ^/redirect_me$1 https://www.google.com permanent"
sed -i "53 i $line1" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_404.html
#echo "Ceci n'est pas une page" > /var/www/html/error_404.html
# segment="\n\terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
# sed -i -e '38i\' -e  "$segment"  /etc/nginx/sites-available/default
sed -i "s/#error_page 404 \/error_404.html;/error_page 404 \/error_404.html;/" /etc/nginx/sites-available/default
#sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
service nginx start