#!/usr/bin/env bash
# Install and configure HAProxy
# shellcheck disable=SC2154

sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.2
sudo apt-get install -y haproxy=2.2.\*
# sudo apt-get install -y haproxy
sudo echo "ENABLED=1" >> sudo /etc/default/haproxy

sudo echo "
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend myservers

backend myservers
    balance roundrobin
    server 11627-web-01 35.175.132.231:80 check
    server 11627-web-02 54.160.116.250:80 check
    option httpchk
    option httpclose
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

# apt-get install -y software-properties-common
# add-apt-repository -y ppa:vbernat/haproxy-1.8
# apt-get update
# apt-get install -y haproxy=1.8.\*

# echo "ENABLED=1" >> /etc/default/haproxy
# mv /etc/haproxy/haproxy.cfg{,.original}
# touch /etc/haproxy/haproxy.cfg

# printf %s "global
#     log 127.0.0.1 local0 notice
#     maxconn 2000
#     user haproxy
#     group haproxy
# defaults
#     log     global
#     mode    http
#     option  httplog
#     option  dontlognull
#     retries 3
#     option redispatch
#     timeout connect  5000
#     timeout client  10000
#     timeout server  10000
# # listen hbnb
# #     bind 0.0.0.0:80
# #     mode http
# #     stats enable
# #     stats uri /haproxy?stats
# #     balance roundrobin
# #     option httpclose
# #     option forwardfor
# #     server 11627-web-01 35.175.132.231:80 check
# #     server 11627-web-02 54.160.116.250:80 check

# frontend http_front
#     bind *:80
#     stats uri /haproxy?stats
#     default_backend http_back

# backend http_back
#     balance roundrobin
#     server 11627-web-01 35.175.132.231:80 check
#     server 11627-web-02 54.160.116.250:80 check
# " >> /etc/haproxy/haproxy.cfg

# service haproxy start