#!/usr/bin/env bash
# Install and configure HAProxy
sudo su
apt-get update -y
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.2
apt-get install -y haproxy=2.2.\*
#sudo apt-get install -y haproxy
echo "ENABLED=1" >> sudo /etc/default/haproxy

echo "
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend myservers

backend myservers
    balance roundrobin
    server 11627-web-01	35.175.132.231 check port 80
    server 11627-web-02 54.160.116.250 check port 80
    option httpchk
    option httpclose
" >> /etc/haproxy/haproxy.cfg

service haproxy start
